BASE_URL = 'https://api.travis-ci.org/'
REPOS_URI = BASE_URL + 'repos/'
REPOS_BY_OWNER = BASE_URL + 'repos.json?owner_name='
BUILDS_URI = BASE_URL + 'builds/'
LOG_URI = BASE_URL + 'jobs/{job_id}/log.txt?deansi=true'